ISI-701-Status-Leiste
it-at-m/isi-backend pull request #102
Opened 2023-09-27 14:56 UTC by TiagoKocevar

**Description**

Abfrage Variable hinzugefügt die angibt ob die Abfrage über dem "normalen Weg" (SACHBEARBEITUNG, FACHREFERATE, BEDARFMELDUNG, ERLEDIGT) oder dem "kurzen Weg" (SACHBEARBEITUNG, ERLEDIGT) geschlossen wurde.

Dies ist relevant für die Statusleiste da nun im Frontend zwei unterschiedliche Statusleisten angezeigt werden.

**Reference**

Issues #701

2023-09-28 06:35 UTC, boal requested changes

2023-09-28 06:35 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    @ReadOnlyProperty
Was wird mit der Annotation `org.springframework.data.annotation.ReadOnlyProperty` bezweckt?

Es handelt sich um eine Annotation welche in einer Entität verhindert, dass dieses Attribut persistiert wird.

https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/annotation/ReadOnlyProperty.html

2023-09-28 06:35 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        final String anmerkung,
Die Attribute anmerkung und schnellesSchließenAbfrage sind in den Javadocs zu dokumentieren.

2023-09-28 06:35 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        final boolean schnellesSchliessenAbfrage
Was bedeutet schnelles schließen und was passiert bei schnelles schließen True oder false?

2023-09-28 06:35 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    private boolean schnellesSchliessenAbfrage;
Was bezweckt dieses Attribut? Soll diese Feld laut der Annotation nur gelesen werden können oder auch zum persistieren verwendet werden?

2023-10-02 13:12 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    private boolean schnellesSchliessenAbfrage;
Also ich möchte dass das Feld nur gelesen wird im Frontend aber nicht per Request abgeändert werden kann. 

Die soll nur über die Methode passieren weshalb ich die ReadOnlyProperty verwendet habe

2023-10-02 13:24 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    @ReadOnlyProperty
Die Logik ist das man die Variable nur über die methoden abändert und nicht über die Requests

2023-10-02 15:00 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    @ReadOnlyProperty
Und habe gelesen das man nur mit der @ReadOnlyProperty Annotation dies bezwecken kann.

2023-10-04 07:43 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    @ReadOnlyProperty
Da es sich bei der AbfrageDto um ein DTO für lesende Zugriffe handelt, kann die Annotation wegfallen.

Falls bei einem DTO bestimmte Attribute nur serialisiert aber nicht deserialisert werden sollen, dann ist die FasterXml-Property `@JsonProperty(access = JsonProperty.Access.READ_ONLY)` zu verwenden.

2023-10-04 08:00 UTC, boal requested changes

2023-10-04 08:00 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    private boolean schnellesSchliessenAbfrage = false;
Bezüglich der Implementierung hier eine generelle Anmerkung.

Im Zustandsautomaten dargestellt in der Architekturdoku gibt es einen Zustandsübergang `KEINE_BEARBEITUNG_NOETIG`, welcher die Abfrage von der Sachbearbeitung direkt auf Erledigt setzt.

Dieser Zustandsübergang ist jedoch aktuell nicht implementiert, würde aber die Anforderung erfüllen. Um eindeutig identifizieren zu können wie eine Abfrage erledigt wurde (z.B. für Darstellung in der GUI), kann der aktuelle Endzustand z.B. von `ERLDEIGT` auf `ERLEDIGT_MIT_FACHREFEREATE` umbenannt werden. Für den Zustandsübergang von der Sachbearbeitung direkt zu erledigt, kann dann ein zusätzlicher Endzustand `ERLEDIGT_OHNE_FACHREFEREATE` implementiert werden.

Folglich ist das Attribut `schnellesSchliessenAbfrage` nicht mehr erforderlich und der Zustandsübergang wird korrekt im Zustandsautomaten abgebildet.

![ISI-Zustandsautmomat_Statusuebergaenge](https://github.com/it-at-m/isi-backend/assets/56300801/d36ae3e1-d51c-49dd-a0f5-f5f3ca9df214)

2023-10-04 08:00 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    @ReadOnlyProperty
siehe auch: https://github.com/it-at-m/isi-backend/pull/102#discussion_r1345364683

2023-10-04 08:12 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    @ReadOnlyProperty
Könntest du das für mich implementieren da ich leider im ITQ bin?

2023-10-04 08:16 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    private boolean schnellesSchliessenAbfrage = false;
Unabhängig von der Implementierung in diesem Branch bzw. im dev-Branch läuft die Beschreibung des Zustandsautomaten mit der Implementierung auseinander. D.h. die Beschreibung im BHB und in der Architekturdoku ist anzupassen.

2023-10-06 15:13 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/dto/AbfrageDto.java
> +    private boolean schnellesSchliessenAbfrage = false;
Doku geupdated und die Änderungen nun eingebaut

2023-10-09 10:05 UTC, boal commented on src/main/java/de/muenchen/isi/security/AuthoritiesEnum.java
> +    ISI_BACKEND_KEINE_BEARBEITUNG_NOETIG_ABFRAGE,
Ist die neue Authority in den ISI-internal aufgenommen, die alte gelöscht und im ssodev importiert?

2023-10-09 10:14 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/security/AuthoritiesEnum.java
> +    ISI_BACKEND_KEINE_BEARBEITUNG_NOETIG_ABFRAGE,
Habe dort eine MR für ISI-Internal: https://git.muenchen.de/isi/isi-internal/-/merge_requests/62 

Weiß nur nicht wann ich die Änderung importieren soll da ja Marco noch andere Storys testet

2023-10-09 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/security/AuthoritiesEnum.java
> +    ISI_BACKEND_KEINE_BEARBEITUNG_NOETIG_ABFRAGE,
Da die Änderung nicht abwärtskompatibel ist, kann der import in ssodev erst kurz vor dem Test geschehen.

2023-10-09 11:17 UTC, boal approved these changes

2023-10-12 13:49 UTC, merged