ISI-627-Dropdown-Einrichtungstraeger
it-at-m/isi-backend pull request #107
Opened 2023-10-19 10:55 UTC by TiagoKocevar

**Description**

Implementierung von unterschiedlichen Einrichtungsträgern. Einmal welche für (EinrichtungstraegerSchulen) Grundschulen und Mittelschulen und welche für (Einrichtungstraeger) GSNachmittagsbetreeung, Haus für Kinder, Kindergarten, Kinderkrippe.

Einrichtungsträger dann von Infrastruktureinrichtung Oberklasse in die Unterklassen verschoben da Sie ja abhängig von der Einrichtung unterschiedliche Einrichtungsträger Enums haben.

Noch Tests und Validierung angepasst

**Reference**

Issues #XXX

2023-10-20 11:03 UTC, boal requested changes

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +                ((GrundschuleDto) value).getSchule().getEinrichtungstraeger().getBezeichnung() != null
Der Validator muss zusätzlich prüfen ob die Variable Einrichtungsträger einen korrekten Enum besitzt.

Also ob der gesetzte Einrichtungsträger für die Einrichtung richtig ist.

![image](https://github.com/it-at-m/isi-backend/assets/56300801/9190aae3-82a2-4ddf-96b2-ba40bd0a12d2)

```java
einrichtungsträger = ((GrundschuleDto) value).getSchule().getEinrichtungstraeger();
((GrundschuleDto) value).getSchule().getEinrichtungstraeger() != null &&
                Einrichtungstraeger.getEinrichtungstraegerSchulen().contains(einrichtungsträger);


```

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/infrastruktureinrichtung/GsNachmittagBetreuungDto.java
> +    private Einrichtungstraeger einrichtungstraeger;
Da der Einrichtungsträger ein Pflichtfeld ist, darf der Wert nicht Null (@NotNull) sein.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/infrastruktureinrichtung/HausFuerKinderDto.java
> +    private Einrichtungstraeger einrichtungstraeger;
Da der Einrichtungsträger ein Pflichtfeld ist, darf der Wert nicht Null (@NotNull) sein.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/infrastruktureinrichtung/KindergartenDto.java
> +    private Einrichtungstraeger einrichtungstraeger;
Da der Einrichtungsträger ein Pflichtfeld ist, darf der Wert nicht Null (@NotNull) sein.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/infrastruktureinrichtung/KinderkrippeDto.java
> +    private Einrichtungstraeger einrichtungstraeger;
Da der Einrichtungsträger ein Pflichtfeld ist, darf der Wert nicht Null (@NotNull) sein.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/infrastruktureinrichtung/SchuleDto.java
> +    private Einrichtungstraeger einrichtungstraeger;
Da der Einrichtungsträger ein Pflichtfeld ist, darf der Wert nicht Null (@NotNull) sein.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/infrastruktureinrichtung/GsNachmittagBetreuung.java
> +    @Column
Da Pflichtfeld `@Column(nullable = false)`.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/infrastruktureinrichtung/HausFuerKinder.java
> +    @Column
Da Pflichtfeld `@Column(nullable = false)`.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/infrastruktureinrichtung/Kindergarten.java
> +    @Column
Da Pflichtfeld `@Column(nullable = false)`.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/infrastruktureinrichtung/Kinderkrippe.java
> +    @Column
Da Pflichtfeld `@Column(nullable = false)`.

2023-10-20 11:03 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/infrastruktureinrichtung/Schule.java
> +    @Column
Da Pflichtfeld `@Column(nullable = false)`.

2023-10-20 11:13 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +                ((GrundschuleDto) value).getSchule().getEinrichtungstraeger().getBezeichnung() != null
Falls der Einrichtungsträger nur bei bestimmten bedingungen ein Pflichfeld ist, dann ist dies ebenfalls zu prüfen. Des Weiteren kann dann die @NotNull-Validierung bei den DTO-Attributen sowie Column(nullable =false) bei den Entitäsatrtibuten entfallen.

2023-10-20 13:51 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +                ((GrundschuleDto) value).getSchule().getEinrichtungstraeger().getBezeichnung() != null
Implementiert

2023-10-23 07:50 UTC, boal requested changes

2023-10-23 07:50 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
>              value.getStatus() != StatusInfrastruktureinrichtung.GESICHERTE_PLANUNG_ERW_PLAETZE_BEST_EINR
Ist die Verundung hier korrekt? Der Status kann ja nie zwei Ausprägungen gleichzeitig besitzen.

2023-10-23 07:50 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
>      private boolean invalidEinrichtungstraegerAllowed(final InfrastruktureinrichtungDto value) {
Was bedeutet der Methodenname InvalidEinrihtungsträger erlaubt?

Der Mehodenname beschreibt nicht, was die Methode prüft.

2023-10-23 07:50 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +                return (
Die beiden folgenden Logiken wiederholen sich mehrmals im Code und sind in eine eigene Methode auszulagern und Unit zu testen.

```java
 return (
                    this.isNotNull(einrichtungstraeger) &&
                    Einrichtungstraeger.getEinrichtungstraegerSchulen().contains(einrichtungstraeger)
                );

```

```java
                return (
                    this.isNotNull(einrichtungstraeger) &&
                    Einrichtungstraeger.getEinrichtungstraeger().contains(einrichtungstraeger)
                );

```

2023-10-23 07:50 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +        return einrichtungstraeger != null && einrichtungstraeger.getBezeichnung() != null;
Weshalb wird auch auf Bezeichung geprüft?

2023-10-23 08:54 UTC, boal requested changes

2023-10-23 08:54 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +    private boolean isNotNull(final Einrichtungstraeger einrichtungstraeger) {
Die Methode wird nicht mehr benötigt.

Die erforderlich Null-Prüfung klann mit Apache-Commons durchgeführt werden. `ObjectUtils.isNotEmtpy(einrichtungstraeger)`

2023-10-23 08:54 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
> +    private boolean isNotStatusBestandOrGesicherteERW(final InfrastruktureinrichtungDto value) {
Methode Unit-esten

2023-10-23 09:07 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/validation/EinrichtungstraegerValidator.java
>              value.getStatus() != StatusInfrastruktureinrichtung.GESICHERTE_PLANUNG_ERW_PLAETZE_BEST_EINR
Nein es sollte eine ODER Operator verwendet werden

2023-10-23 10:00 UTC, boal approved these changes

2023-10-23 12:25 UTC, merged