Isi 354 name abfrage unique
it-at-m/isi-backend pull request #11
Opened 2023-01-23 14:32 UTC by DomixD

**Description**
Der Name einer Abfrage darf nur einmal vorkommen.

**Reference**

Issues ISI-354

2023-01-23 15:32 UTC, boal requested changes

2023-01-23 15:32 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
> +    @Column(nullable = false, unique = true)
Die im Repository mittels findBy nach dem Namen direkt in der Datenbank gesucht wird und wegen eines fehlenden Suchindexes diese Suche sequentiell durchgeüfrht wird, sollte für das Attribute `nameAbfrage` ein Suchindex erstellt definiert werden. 

Somit wird bei vielen Entitäten die Suche erheblich beschleunigt.

```java
@Table(
        indexes = {
                @Index(name = "name_abfrage_index", columnList = "nameAbfrage")
        }
)

```

2023-01-23 15:32 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
> +    @Column(nullable = false, unique = true)
Da es sich um ein Embeddable handelt muss der Index evtl in der Enittätsklasse definiert werden.

2023-01-23 15:32 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Bauvorhaben.java
> +    @Column(nullable = false, unique = true)
Die im Repository mittels findBy nach dem Namen direkt in der Datenbank gesucht wird und wegen eines fehlenden Suchindexes diese Suche sequentiell durchgeüfrht wird, sollte für das Attribute nameAbfrage ein Suchindex erstellt definiert werden.

Somit wird bei vielen Entitäten die Suche erheblich beschleunigt.

```java
@Table(
        indexes = {
                @Index(name = "name_vorhaben_index", columnList = "nameVorhaben")
        }
)
```

2023-01-23 15:32 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
> +    @Column(nullable = false, unique = true)
Der Name der Spalte im Attribut "columnList" muss so wie der tatsächeliche Spaltenname benannt sein. Dies kannst du am besten beim Hochfahren des Backends im Profil lokal prüfen.

2023-01-23 15:32 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/InfrastrukturabfrageRepository.java
> +    Optional<Infrastrukturabfrage> findByAbfrage_NameAbfrageIgnoreCase(final String nameAbfrage);
Der Unterstrich ist nicht unbedingt erforderlich. Tut aber auch nicht weh. :-)

2023-01-25 08:11 UTC, DomixD commented on src/main/java/de/muenchen/isi/infrastructure/repository/InfrastrukturabfrageRepository.java
> +    Optional<Infrastrukturabfrage> findByAbfrage_NameAbfrageIgnoreCase(final String nameAbfrage);
Hat intellij so vorgeschlagen^^

2023-01-25 08:55 UTC, boal approved these changes

2023-02-03 08:50 UTC, merged