ISI-906 Import von Stammdaten in Datenbank
it-at-m/isi-backend pull request #113
Opened 2023-11-07 08:29 UTC by TiagoKocevar

**Description**

Die Tabellen SobonOrientierungswerte und StaedtebaulicheOrientierungswerte sollten in die Datenbank als Stammdaten hinterlegt werden für die Berechnung. 

Abänderung von Wohnungstyp zu Förderart und Klassen SobonOrientierungswerte + StaedtebaulicheOrientierungswerte  sind nun in der Klasse SobonJahre. 

SobonJahre hat beide Tabellen vom gleichem Jahr und gibt an ab wann sie Gültig sind. 

Dies habe ich mit Alex als Klasse besprochen für die berechnung.

**Reference**

Issues #906

2023-11-09 09:28 UTC, boal requested changes

2023-11-09 09:28 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonJahr.java
> +public class SobonJahr extends BaseEntity {
Weshalb wurden in diesem Branch die Stammdaten für die Sobon-Orientierungswerte implementiert? Dieser Branch umfasst die Task ISI-927 zur Umlegung der Fördermixe.

2023-11-09 10:58 UTC, boal requested changes

2023-11-09 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonJahr.java
> +public class SobonJahr extends BaseEntity {
Weshalb wird die Entität `SobonJahr` benannt und enthält ein Attribut `jahr`. 

Die für die Berechnung zu wählenden Stammdaten sind mittels des Attributs `gueltigAb` ermittelbar.

Beispiel:
- Stammdatum A → Gültig ab 01.01.2020
- Stammdatum B → Gültig ab 01.08.2025


Das Stammdatum A ist somit vom 01.01.2020 bis einschließlich 31.07.2025 gültig. Wird bei der Berechnung anstelle des "Jahr für Sobon-Orientierungswerte" eine Datumsangabe 01.01.2022 (Abgeleitet aus dem in der GUI gewählten Sobon-Jahr)  gewählt, so wird für die Berechnung das Stammdatum A verwendet.  Wird als Datumsangabe 06.06.2030 gewählt, so wird für die Berechnung das Stammdatum B angezogen.

2023-11-09 11:49 UTC, boal requested changes

2023-11-09 11:49 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonOrientierungswert.java
>      private BigDecimal einwohnerJahr1NachErsterstellung;
Die Attribute `mittelwertEinwohnerJeWohnung`, `perzentil75ProzentEinwohnerJeWohnung` sowie `perzentil75ProzentGerundetEinwohnerJeWohnung` brauchen meiner Meinung nach nicht gespeichert werden. 

Diese Informationen sind rechnerisch ermittelbar.

2023-11-09 11:49 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonOrientierungswert.java
>      private BigDecimal einwohnerJahr1NachErsterstellung;
Die Attribute `faktor1` bzw. `faktor` werden in der Excelvorlage zur Ermittlung des 75-Percentils verwendet.
Die Berechnung des 75-Percentils mit dem Faktor entspricht nämlich nicht dem eigentlichen 75-Percentil (bzw 3.-Quantil).

Die Frage ist, für welche fachlichen Berechnungen der Faktor noch verwendet wird.

2023-11-09 13:32 UTC, boal requested changes

2023-11-09 13:32 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonJahr.java
> +    private List<StaedtbaulicherOrientierungwert> staedtebaulicheOrientierungswerte;
Die Listen-Attribute `staedtebaulicheOrientierungswerte` und `sobonOrientierungswerte` sollten jeweils in eine eigene Klasse mit dem Attribut `gueltigAb` ausgelagert werden.

Somit ist gewährleistet, dass die Stammdaten der `StaedtebaulicheOrientierungswerte` und `SobonOrientierungswerte` bei Bedarf unterschiedliche gueltigAb-Werte besitzen darf.

2023-11-10 08:50 UTC, boal requested changes

2023-11-10 08:50 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/SobonJahrRepository.java
> +        final Integer jahr,
Das jahr ist durch ein Datum zu ersetzen, da die Stammdaten mit einem GültiAb versehen werden sollen.

Entität A -> gültig Ab 01.01.2020
Entität B -> gültig Ab 05.05.2025

Dann ist die Entität A gültig vom 01.01.2020 bis einschließlich 04.05.2025

2023-11-10 08:50 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/SobonJahrRepository.java
> +    Optional<StaedtbaulicherOrientierungwert> findByJahrAndStaedtebaulicheOrientierungswerteFoerderArt(
Das jahr ist durch ein Datum zu ersetzen, da die Stammdaten mit einem GültiAb versehen werden sollen.

Entität A -> gültig Ab 01.01.2020
Entität B -> gültig Ab 05.05.2025

Dann ist die Entität A gültig vom 01.01.2020 bis einschließlich 04.05.2025

2023-11-13 16:23 UTC, TiagoKocevar commented
Habe auf einem neuen Branch angefangen und deswegen eine neue MR eröffnet https://github.com/it-at-m/isi-backend/pull/116

2023-11-13 16:23 UTC, closed without merging