ISI-927-Umlegung-Foerderarten
it-at-m/isi-backend pull request #115
Opened 2023-11-09 13:07 UTC by TiagoKocevar

**Description**

Umlegungs Klasse erstellt welche die Förderarten die Umgelegt werden müssen speichert.

Da es nur für die Berechnung nötig ist gibt es keine DTO Klasse

Diese MR wurde neu erstelllt da ich denn ISI-906 Branch noch in meinen drinnen hatte und nun alles resetet habe.

**Reference**

Issues #XXX

2023-11-09 13:08 UTC, TiagoKocevar commented
Boxi: 

https://github.com/it-at-m/isi-backend/pull/114#discussion_r1387686197

Die Umrechnung der Förderarten ist durch diese Stammdatenentität auf zwei Zielförderarten begrenzt.

Das Stammdatum ist generisch zu implementieren. Beispiel:

Die Zielumlage (hier Foerderart) kann in der Stammdatenentität sogar als JSON-Attribut hinterlegt werden, da es sich im Sinne von DDD um ein Value-Object handelt. Somit wird die UmlageFoerderart keine eigene Tabelle erstellt.

2023-11-09 13:09 UTC, TiagoKocevar commented
Boxi
https://github.com/it-at-m/isi-backend/pull/114#discussion_r1387687275



Die Benennung der Entität Umlegung ist nicht eindeutig. Was wird hier umgelegt?

2023-11-09 13:10 UTC, TiagoKocevar commented
Boxi :
https://github.com/it-at-m/isi-backend/pull/114#discussion_r1387694940

Wo befindet sich die Serviceklasse zur Umlegung einer Förderart?

Die Serviceklasse erwartet eine Liste von Förderarten mit Prozentwerten (List<FoerderartModel>), legt diese entsprechend um und gibt die umgelegte Liste mit nicht umzulegenden und den umgelegten Förderarten samt Prozentwerten zurück.


Tiago: 
https://github.com/it-at-m/isi-backend/pull/114#discussion_r1387918625
Ich habe mich mit Alex abgesprochen und er meinte ich muss nur die Stammdaten einspielen und er macht die Umlegungsservice Klasse

2023-11-09 13:11 UTC, TiagoKocevar commented
Boxi:
https://github.com/it-at-m/isi-backend/pull/114#discussion_r1387716622

Da die selbe Förderart (Attribut bezeichnung) Umrechnungsschlüssel mit unterschiedlichen Gültigkeitszeiträumen besitzen kann (Attribut gueltigAb), ist für die beiden Attribute bezeichnung und gueltigAb ein kombinierter Fachlicher Tabellenschlüssel zu definieren. Ansonsten ist es in der Tabelle möglich für einen Förderart mehrere Umlegungsentitäten mit dem selben gueltigAb-Datum anzulegen.

2023-11-09 15:05 UTC, boal requested changes

2023-11-09 15:05 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/UmlegungFoerderarten.java
> +    // Die Klasse Foerderart existiert bereits.
Kommentar entfernen

2023-11-09 15:20 UTC, boal requested changes

2023-11-09 15:20 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findBybezeichnung(final String bezeichnung);
Die Methode benötigt einen zweiten Parameter für ein Datum welche die Korrekte `UmlegungFoerderarten` bezogen auf gültigAb findet.

Beispiel für Förderart A:

Umlegung Foerderarten A (die erste) -> gültigAb 01.01.1900
Umlegung Foerderarten A  -> gültigAb 15.02.2000
Umlegung Foerderarten A  -> gültigAb 01.01.2020

findBybezeichnung(final String bezeichnung, final LocalDate datum)

- findBybezeichnungXXX("A", 6.12.1982) -> Gibt **Umlegung Foerderarten A (die erste) -> gültigAb 01.01.1900** zurück.
- findBybezeichnungXXX("A", 15.2.2000) -> Gibt **Umlegung Foerderarten A  -> gültigAb 15.02.2000** zurück.
- findBybezeichnungXXX("A", 02.02.2009) -> Gibt **Umlegung Foerderarten A  -> gültigAb 15.02.2000** zurück.
- findBybezeichnungXXX("A", 01.01.2020) -> Gibt **Umlegung Foerderarten A  -> gültigAb 01.01.2020** zurück.
- findBybezeichnungXXX("A", 01.01.2055) -> Gibt **Umlegung Foerderarten A  -> gültigAb 01.01.2020** zurück.

2023-11-09 15:23 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findBybezeichnung(final String bezeichnung);
Diese Repository-Methode am besten mit dem Spring-Context testen.

2023-11-09 15:26 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findBybezeichnung(final String bezeichnung);
Die aktuelle Methode würde immer nur die **Umlegung Foerderarten A (die erste) -> gültigAb 01.01.1900** zurückgeben, weil mehrer mit der Förderart A existieren.

2023-11-09 15:27 UTC, boal requested changes

2023-11-09 15:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/model/stammdaten/UmlegungFoerderartenModel.java
> +    private String bezeichnung;
Die Bezeichnung ist auch die Förderart. Also die Förderart welche umgelegt werden soll.

2023-11-09 15:55 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/domain/model/stammdaten/UmlegungFoerderartenModel.java
> +    private String bezeichnung;
Ja die Bezeichnung sagt das diese Förderart umgelegt werden soll. Da die Förderarten auch eine bezeichnung haben habe ich diese Variable eben so gennant

2023-11-09 15:55 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findBybezeichnung(final String bezeichnung);
Tests added

2023-11-10 08:18 UTC, boal requested changes

2023-11-10 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findByBezeichnungAndGueltigAbBeforeOrderByGueltigAbDesc(
Anstelle `findBy...` besser `findFirstBy...` verwenden. Da hier bereits im SQL-Statement die Ergebnismenge auf ein Element reduziert wird. Somit wird die Datenextraktion beschleunigt, da in der Datenbank due Datenextraktion nach dem ersten Element endet.

[findFirst](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.limit-query-result)

2023-11-10 08:24 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findByBezeichnungAndGueltigAbBeforeOrderByGueltigAbDesc(
Das SQL-Statement wird dann ungefähr so aussehen.

```sql

SELECT y,x,z,... FROM Testinger
WHERE xxxx
FETCH FIRST 1 ROWS ONLY;

```

2023-11-10 08:28 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/infrastructure/repository/stammdaten/UmlegungFoerderartenRepository.java
> +    Optional<UmlegungFoerderarten> findByBezeichnungAndGueltigAbBeforeOrderByGueltigAbDesc(
Danke für die Erklärung wusste das noch nicht

2023-11-10 09:27 UTC, boal approved these changes

2023-11-10 11:09 UTC, merged