ISI-906 Import Stammdaten Sobon-Werte in Datenbank auf Basis CSV
it-at-m/isi-backend pull request #116
Opened 2023-11-13 16:22 UTC by TiagoKocevar

**Description**

Die Tabellen SobonOrientierungswerte und StaedtebaulicheOrientierungswerte sollten in die Datenbank als Stammdaten hinterlegt werden für die Berechnung.

Abänderung von Wohnungstyp zu Förderart und Klassen SobonOrientierungswerte + StaedtebaulicheOrientierungswerte sind nun in der Klasse SobonJahre.

SobonJahre hat beide Tabellen vom gleichem Jahr und gibt an ab wann sie Gültig sind.

Dies habe ich mit Alex als Klasse besprochen für die berechnung.

Reference

Issues #906

2023-11-13 16:22 UTC, TiagoKocevar commented
Ich möchte auf die andere MR verweisen da ich auf diesem Branch neu gestartet habe. https://github.com/it-at-m/isi-backend/pull/113

2023-11-14 09:14 UTC, boal requested changes

2023-11-14 09:14 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/stammdaten/SobonOrientierungswertSozialeInfrastrukturDto.java
>  public class SobonOrientierungswertSozialeInfrastrukturDto extends BaseEntityDto {
Werden die DTOs sowie die dazugehörige Controllerklassen aktuell benötigt? Diese können entfernt werden, da die Stammdaten im Backend für weitere Berechnungen verwendet werden.

2023-11-14 09:14 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/stammdaten/StaedtebaulicheOrientierungswertDto.java
>  public class StaedtebaulicheOrientierungswertDto extends BaseEntityDto {
Werden die DTOs sowie die dazugehörige Controllerklassen aktuell benötigt? Diese können entfernt werden, da die Stammdaten im Backend für weitere Berechnungen verwendet werden.

2023-11-14 09:14 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +        if ((deferDatasourceInit != null && deferDatasourceInit.booleanValue())) {
Hier können die BooleanUtils verwendet werden. z.B. `BooleanUtils.isTrue`

[BooleanUtils.isTrue](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/BooleanUtils.html#isTrue-java.lang.Boolean-)

2023-11-14 09:14 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +            log.info("START LOADING STAMMDATEN");
Welche Stammdaten werden geladen?

2023-11-14 09:14 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +    private static final String PATH = "csv/";
Pfad zum Ordner der CSV-Dateien als Property vorhalten und in Propertydatei pflegen.

2023-11-14 09:18 UTC, boal requested changes

2023-11-14 09:18 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +    public void addSobonJahre(String dateipfad) {
Alternativ können zur Reviewanmerkung https://github.com/it-at-m/isi-backend/pull/116#discussion_r1392240170 die relativen Dateipfade zu den CSV-Dateien als Listen in einer Property jeweils für die SobonSozialeinfrastruktur dund SobonOrientierungswerte vorgehalten werden.

`property.x.y: csv/SoBoNOrientierungswerteSozialeInfrastruktur2014.csv,csv/SoBoNOrientierungswerteSozialeInfrastruktur2017.csv,...`

Somit brauchen die Dateipfade nicht mehr hartkodiert werden.

2023-11-14 09:24 UTC, boal requested changes

2023-11-14 09:24 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +    public void addSobonJahre(String dateipfad) {
Die Properties könnnen dann analog der Property `file.mimetypes.allowed` in der Serviceklasse als Liste von Strings eingelesen werden.

2023-11-14 11:29 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/stammdaten/SobonOrientierungswertSozialeInfrastrukturDto.java
>  public class SobonOrientierungswertSozialeInfrastrukturDto extends BaseEntityDto {
entfernt

2023-11-14 11:32 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +        if ((deferDatasourceInit != null && deferDatasourceInit.booleanValue())) {
done

2023-11-14 11:32 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/stammdaten/StaedtebaulicheOrientierungswertDto.java
>  public class StaedtebaulicheOrientierungswertDto extends BaseEntityDto {
entfernt

2023-11-14 11:32 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +            log.info("START LOADING STAMMDATEN");
beschrieben

2023-11-14 11:32 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +    public void addSobonJahre(String dateipfad) {
done

2023-11-14 15:00 UTC, boal approved these changes, later dismissed

2023-11-15 11:49 UTC, boal requested changes

2023-11-15 11:49 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonOrientierungswertSozialeInfrastruktur.java
> +    private BigDecimal stammwertArbeitsgruppe;
Beträgt die Anzahl der Nachkommestallen bei `stammwertArbeitsgruppe` nicht ebenfalls 4 (scale = 4)?

2023-11-15 11:53 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonOrientierungswertSozialeInfrastruktur.java
> +    private BigDecimal stammwertArbeitsgruppe;
Es hat doch im Code Scale 4

2023-11-15 11:55 UTC, boal approved these changes

2023-11-15 11:55 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/SobonOrientierungswertSozialeInfrastruktur.java
> +    private BigDecimal stammwertArbeitsgruppe;
Ups. Stimmt. Die Zeilen drüber sind ja entfernt worde! :-)

2023-11-15 13:02 UTC, merged