ISI-907-Versorgungsquote und Gruppenstärke
it-at-m/isi-backend pull request #117
Opened 2023-11-20 10:21 UTC by TiagoKocevar

**Description**

Erstellung einer Entität welche die Versorgungsquote und Gruppenstärke einer Bildungseinrichtung beinhaltet. 

**Reference**

Issues #907

2023-11-20 10:22 UTC, TiagoKocevar commented
Der commit hat einen fehler anstatt "hinterlägt" natürlich "hinterlegt" 😑

2023-11-20 11:00 UTC, boal requested changes

2023-11-20 11:00 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/VersorgungsquoteGruppenstaerke.java
> +    private String bildungseinrichtungBezeichnung;
Wäre es hier nicht besser eine Enum zu definieren?

Leider kann der Enum für den Typ der Infrastruktureinrichtung nicht verwendet werden, da dieser keinen Hort kennt.

Hier ist ggf. ein eingener Enum zu definieren.

![image](https://github.com/it-at-m/isi-backend/assets/56300801/e411f1f3-4999-4614-a9b7-5ee97000ed40)

2023-11-20 11:00 UTC, boal commented on src/main/java/de/muenchen/isi/domain/model/stammdaten/VersorgungsquoteGruppenstaerkeModel.java
> +    private int versorgungsquotePlanungsursaechlich;
Das Attribut ist für einen Prozentwert gedacht.

Hier sollte als Datentyp ein BigDecimal verwendet werden. Folglich lässt sich mit diesen Werten besser rechnen.

Beispiel: 61,2% -> 0,612

Die Wertebereich darf zwischen 0 und 1 liegen.

2023-11-20 11:00 UTC, boal commented on src/main/java/de/muenchen/isi/domain/model/stammdaten/VersorgungsquoteGruppenstaerkeModel.java
> +    private int versorgungsquoteSobonUrsaechlich;
Das Attribut ist für einen Prozentwert gedacht.

Hier sollte als Datentyp ein BigDecimal verwendet werden. Folglich lässt sich mit diesen Werten besser rechnen.

Beispiel: 61,2% -> 0,612

Die Wertebereich darf zwischen 0 und 1 liegen.

2023-11-20 11:38 UTC, boal requested changes

2023-11-20 11:38 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/VersorgungsquoteGruppenstaerke.java
> +    @DecimalMin("0.0")
Die Javax-Validierung haben hier keine Auswirkungen, da Spring die Validierung durchführt.

2023-11-20 12:00 UTC, boal requested changes

2023-11-20 12:00 UTC, boal commented on src/test/java/de/muenchen/isi/infrastructure/repository/stammdaten/VersorgungsquoteGruppenstaerkeRepositoryTest.java
> +    void findUmlegungFoerderartenbyBezeichnungAndDatum() {
Die Persistierung der Grenzfälle (0 und 1) und eindeutig nicht erlaubte Werte testen.

Dabei auch Werte wie `new BigDecimal("0.000")`, `new BigDecimal("0")`,  `new BigDecimal("0.0")` und `new BigDecimal("1.000")`, `new BigDecimal("1")`,  `new BigDecimal("1.0")` testen.

2023-11-20 14:03 UTC, boal approved these changes

2023-11-20 15:28 UTC, boal requested changes

2023-11-20 15:28 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/VersorgungsquoteGruppenstaerke.java
> +    private Bildungseinrichtung bildungseinrichtung;
Der Enum Bildungseinrichtung kann entfallen, da es bereits den Enum "Einrichtungstyp" gibt.

2023-11-22 09:03 UTC, boal approved these changes

2023-11-22 11:49 UTC, merged