ISI-697 Hebung Spring Java
it-at-m/isi-backend pull request #126
Opened 2023-12-14 07:22 UTC by boal

**Description**

Hebung:

- Spring-Boot
- Spring-Cloud
- Elasticsearch
- Java

**Reference**

ISI-697

2023-12-20 13:25 UTC, ejcsid requested changes

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
>       * @throws IOException sobald ein Fehler beim Lesen der Datei auftritt.
Es wird keine MultipartFile sondern ein FileInputStream zurückgegeben.

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
>      }
In der aufgerufenen Methode wird ein FileInputStream erzeugt. Dieser muss auch wieder geschlossen werden. Siehe: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/FileInputStream.html ("https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/FileInputStream.html")

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
>      }
In der aufgerufenen Methode wird ein FileInputStream erzeugt. Dieser muss auch wieder geschlossen werden.

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +        return new FileInputStream(tempFile);
Wo wird dieser InputStream geschlossen?

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +            this.importStaedtebaulicheOrientierungswerte(csvImportFile.getInputStream());
Der Stream sollte wieder geschlossen werden.

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +        try (final InputStreamReader csvInputStreamReader = new InputStreamReader(csvImportFile)) {
Der Reader sollte wieder geschlossen werden

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +        } catch (final IOException exception) {
Der Stream sollte wieder geschlossen werden.

2023-12-20 13:25 UTC, ejcsid commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +        try (final InputStreamReader csvInputStreamReader = new InputStreamReader(csvImportFile)) {
der Reader sollte wieder geschlossen werden

2023-12-20 13:39 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
>       * @throws IOException sobald ein Fehler beim Lesen der Datei auftritt.
done

2023-12-20 13:52 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
>      }
oh ja. done

2023-12-20 13:53 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +            this.importStaedtebaulicheOrientierungswerte(csvImportFile.getInputStream());
oh ja. done

2023-12-20 13:53 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
> +        return new FileInputStream(tempFile);
Wird nun in den Methoden geschlossen, die diesen Stream verwenden.

2023-12-20 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +        try (final InputStreamReader csvInputStreamReader = new InputStreamReader(csvImportFile)) {
Der Inputstreamreader wird implizit durch `try (final InputStreamReader csvInputStreamReader = new InputStreamReader(csvImportFile))` geschlossen sobald der Try-Block verlassen wird.

2023-12-20 13:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +        } catch (final IOException exception) {
oh ja. done

2023-12-20 13:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/StammdatenImportService.java
> +        try (final InputStreamReader csvInputStreamReader = new InputStreamReader(csvImportFile)) {
Wird implizit bei verlassen des Try-Block geschlossen.

2023-12-20 14:06 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/ImportStammdatenFromFile.java
>      }
oh ja. done

2023-12-20 14:44 UTC, ejcsid approved these changes, later dismissed

2024-01-15 10:26 UTC, ejcsid approved these changes

2024-01-15 12:56 UTC, merged