Add size for nameAbfrage
it-at-m/isi-backend pull request #13
Opened 2023-01-25 10:19 UTC by DomixD

**Description**

Das Feld nameAbfrage wurde auf 70 Zeichen beschränkt. Das Feld nameAbfragevariante aus dem issue ISI-299 hab ich weder im Frontend noch Backend gefunden.

**Reference**

Issues ISI-299

2023-01-26 14:30 UTC, boal requested changes

2023-01-26 14:30 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
>      private String nameAbfrage;
Das Attribut `nameAbfrage` der DTO-Klasse `de.muenchen.isi.api.dto.AbfrageDto` muss entsprechend der Column-Defintion  mit `@Size`  validiertwerden, da die Validierung der eingehenden Request über die DTO-Klassen in den Controller gemacht wird.

```java
@Data
public class AbfrageDto {

...

    @Size(max = 70)
    @NotBlank
    private String nameAbfrage;

...

}

```

2023-01-26 15:16 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
>      private String nameAbfrage;
Falls die größe des Bauvorhabens ebenso auf eine Anzahl an Zeichen beschränkt ist, am besten ebenso im DTO validieren und in der Entity beschränken.

2023-01-30 08:25 UTC, DomixD commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
>      private String nameAbfrage;
Wäre das dann nicht doppelt drin? Das mit @Column(length = 70) hab ich dort so gemacht, weil @Size mit Embeddable nicht funktioniert.

Also muss man das dann pro Entity und DTO machen oder reicht ein was? @boal

2023-02-01 11:39 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Abfrage.java
>      private String nameAbfrage;
Eine da es sich bei der Längenbeschränkung um ein Constraint in der DB und auch um eine Validierung handelt, sollte die Längenbeschrännkung auch im DTO hinterlegt werden. Die Validierung im DTO bildet die Validierung in der GUI ab.

Des Weiteren sollte jegliche Validierung im DTO gemacht werden. Eine Aufteilung von Validierung in Entität und DTO müssen wir vermeiden, da man ansonsten nicht mehr weiß wo welche Validierung stattfindet.

2023-02-01 14:49 UTC, boal approved these changes

2023-02-03 09:46 UTC, merged