ISI-317 Zustandsautomat
it-at-m/isi-backend pull request #14
Opened 2023-01-27 10:00 UTC by TiagoKocevar

Ich habe die Status Änderung mit Hilfe der Spring State Machine umgesetzt. 

Auf Confluence bitte das Statusübergangsmodell anschauen für mehr Information darüber.

**Reference**

Issues #317

2023-01-27 12:58 UTC, boal requested changes

2023-01-27 12:58 UTC, boal commented on pom.xml
> +            <version>3.2.0</version>
Version in den Properties der pom.xml definieren.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @Operation(summary = "Setzt eine Infrastrukturabfrage auf OFFEN genaue Statusänderungdefinition in {@link  StateMachineConfiguration}")
Bei @Operation vor den Status das Wort Status setzen. Somit ist klar das der Status offen gemeint ist.

Beispieltext:

`Setzt eine Infrastrukturabfrage auf Status OFFEN`

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @Operation(summary = "Setzt eine Infrastrukturabfrage auf OFFEN genaue Statusänderungdefinition in {@link  StateMachineConfiguration}")
Der Satz ` genaue Statusänderungdefinition in {@link  StateMachineConfiguration}` sollte in die Javadoc der Klasse aufgenommen werden.

Der Link `{@link  StateMachineConfiguration}` ist eine Javadocverlinkung und funktioniert nicht in den API-Docs.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @Operation(summary = "Setzt eine Infrastrukturabfrage auf OFFEN genaue Statusänderungdefinition in {@link  StateMachineConfiguration}")
Die Anmerkung betrifft alle `@Operation`-Anotation in dieser Klasse.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +            @ApiResponse(responseCode = "200", description = "OK -> Abfrage wurde erfolgreich freigegeben."),
Wurde hier die Abfrage erfolgreich freigegeben?

Betrifft jede @ApiResponse-Annotation in der Klasse mit Status 200.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT -> Die Abfrage konnte aufgrund des aktuellen Status nicht freigegeben werden.", content = @Content(schema = @Schema(implementati
Hier findet keine Freigabe statt. Bzw. es ist nicht möglich das eine Freigabe nicht durchgeführt werden kann.

Betrifft jede @ApiResponse-Annotation in der Klasse mit Status 409.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/configuration/StateMachineConfiguration.java
> +    public void configure(StateMachineStateConfigurer<StatusAbfrage, StatusAbfrageEvents> states) throws Exception {
Zwischen allen Methoden und Klassenanfang sowie Klassenende eine Leerzeile einfügen.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException falls die Abfrage nicht gefunden werden kann.
@throws für `AbfrageStatusNotAllowedException` ergänzen. 

Betrifft alle Methoden der Klasse.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +    private final StateMachineFactory<StatusAbfrage, StatusAbfrageEvents> stateMachineFactory;
Leerzeile zwischen den Variablen einer Klasse.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +    /**
Leerzeilen zischen den einzelnen Methode.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +    private static final String ABFRAGE_ID_HEADER = "abfrage_id";
Konstanten gehören in einer Klasse ganz nach oben. Danach folgende die Variablen, danach ggf. ein Ctor und danach die Methoden.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * Ausserdem definieren wir eine preStateChange Listener der bei einer Statusänderung den Status in der DB aktualiesiert.
Typo `aktualiesiert` -> `aktualisiert`

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        // Hier habe ich ein EntityNotFoundExeption Array definiert damit ich die Fehlermeldung im preStateChange Listener abfangen kann und
Bei Dokumentation die Ich-Form vermeiden und in einem neutralen unpersönlicher Stil schreiben.

z.B. Definieren einer EntityNotFoundException um Fehlermeldung im preStateChange-Listener abzufengen ...

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                                        .ifPresent(fahrzeugId -> {
Was bedeutet die Variable `fahrzeugId` im fachlichen Kontext?

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                                                UUID.class.cast(msg.getHeaders().getOrDefault(ABFRAGE_ID_HEADER, UUID.randomUUID())))
Es wird in diesem Code das Objekt des Headers "abfrage_id" herausgeholt und dann gecastet. Falls der Header nicht exitiert wird eine zufällige UUID erzeugt.

Les- und Wartbarer wäre doch evtl folgendes:

```java

                                        final UUID abfrageId;
                                        final MessageHeaders headers = msg.getHeaders();
                                        if (headers.containsKey(ABFRAGE_ID_HEADER)) {
                                            abfrageId = (UUID) headers.get(ABFRAGE_ID_HEADER);
                                        } else {
                                            throw EineException();
                                        }

```

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        final EntityNotFoundException[] entityNotFoundException = new EntityNotFoundException[1];
Werden im Code mehrere Exception erwartet?

Falls nein weshalb wird ein Array verwendet?

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        if (entityNotFoundException[0] != null) {
Washalb wird ein Array bei den Exceptions verwendet.

Der Array besitzt die Länge 1.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/enums/lookup/StatusAbfrageEvents.java
> +
Enums entweder alle mit oder ohne Leerzeilen.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +    private void sendEvent(UUID id, StatusAbfrageEvents event, StateMachine<StatusAbfrage, StatusAbfrageEvents> stateMachine) throws AbfrageStatusNotAllowedException {
Alle Methodenparameter als final deklarieren.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                    });
Einrückungen und Formatierungen sind fehlerhaft.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        final AbfrageStatusNotAllowedException[] abfrageStatusNotAllowedException = new AbfrageStatusNotAllowedException[1];
Wird hier ein Array mit der Länge 1 benötigt?

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        result.subscribe(smer -> {
Was ist ein `smer`? Ersetzen durch `consumer`.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                .doWithAllRegions(sma -> {
Was ist ein `sma`? Ersetzen durch `stateMachineAccess`.

2023-01-27 12:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                                                UUID.class.cast(msg.getHeaders().getOrDefault(ABFRAGE_ID_HEADER, UUID.randomUUID())))
Evtl in eigene Methode auslagern um den Code in dieser Klasse besser lesen und auch testen zu können.

Für den ausgelagertn Code Unit-Tests definieren.

2023-01-27 13:01 UTC, boal requested changes

2023-01-27 13:01 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID}  um die Abfrage aus der DB zu hollen.
Typo `hollen` -> zu `holen`

2023-01-27 13:25 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                .doWithAllRegions(sma -> {
`doWithAllRegions` kann in selbe Zeile wie `getStateMachineAccessor`.

2023-01-30 13:49 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        final EntityNotFoundException[] entityNotFoundException = new EntityNotFoundException[1];
Weil Alex und ich nicht wussten wie wir die Exceptions aus dem Lambda "raushollen" können. Und da hat IntelliJ vorgeschlagen das man ein Array definieren soll in welchem man die Fehlermeldung zuweist und danach überprüfen kann ob ein fehler geworfen wurde.

2023-01-30 13:52 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        final AbfrageStatusNotAllowedException[] abfrageStatusNotAllowedException = new AbfrageStatusNotAllowedException[1];
Gleicher Grund wie bei der Entity Not Found Exception im Interceptor

2023-02-01 11:40 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        final EntityNotFoundException[] entityNotFoundException = new EntityNotFoundException[1];
überarbeitet

2023-02-01 11:40 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        if (entityNotFoundException[0] != null) {
überarbeitet

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/abbrechen")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`

```suggestion
    @PutMapping("{id}/abbrechen")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/angabe-anpassen")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`

```suggestion
    @PutMapping("/{id}/angabe-anpassen")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/weitere-abfragevarianten-anlegen")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`

```suggestion
    @PutMapping("/{id}/weitere-abfragevarianten-anlegen")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/keine-zusaetzliche-abfragevariante")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`

```suggestion
    @PutMapping("/{id}/keine-zusaetzliche-abfragevariante")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/zusaetzliche-abfragevariante-anlegen")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`


```suggestion
    @PutMapping("/{id}/zusaetzliche-abfragevariante-anlegen")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/speicher-der-varianten")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`

```suggestion
    @PutMapping("/{id}/speicher-der-varianten")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/keine-bearbeitung-noetig")
Kann man nicht über die Klasse die Annotation schreiben 
`@RequestMapping(value = CONTROLLER_PATH)` um doppelten Code und Tippfehler zu vermeiden.

Als Konstante setzen:
`public static final String CONTROLLER_PATH = "infrastruktur-abfrage";`

```suggestion
    @PutMapping("/{id}/keine-bearbeitung-noetig")
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/verschicken-der-stellungnahme")
Siehe oben

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/bedarfsmeldung-erfolgt")
siehe oben

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/speicher-von-soz-infrastruktur-versorgung")
siehe oben

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/configuration/StateMachineConfiguration.java
> +     * Legt fest welche Events es alle geben soll. ANGELEGT ist der Anfangstatus und ABBRUCH ist der Endstatus
```suggestion
     * Legt alle verfuegbaren Events fest. ANGELEGT ist der Anfangstatus und ABBRUCH ist der Endstatus.
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/configuration/StateMachineConfiguration.java
> +     * Für mehr Informationen zu den Statusänderungen bitte auf Confluence nachschauen
```suggestion
     * Für mehr Informationen zu den Statusänderungen bitte auf Confluence nachschauen.
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/configuration/StateMachineConfiguration.java
> +     * @throws Exception falls ein Fehler passiert
Bisschen genauer definieren welche Art von Fehler.

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/configuration/StateMachineConfiguration.java
> +                // Alle Events von ERLDEDIGT
Leerzeile davor einfügen.
```suggestion

                // Alle Events von ERLDEDIGT
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.
```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
>       * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID} um die Abfrage zu finden.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage zu finden
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException          falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id vom Typ {@link UUID}  um die Abfrage aus der DB zu holen.
```suggestion
     * @param id vom Typ {@link UUID}  um die Abfrage aus der DB zu holen
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException falls die Abfrage nicht gefunden werden kann.
Anmerkung um es einheitlich mit bereits bestehenden Javadocs zu machen.

```suggestion
     * @throws EntityNotFoundException falls die Abfrage nicht gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                 * Verhalten siehe {@link StateMachineInterceptor#preTransition(StateContext)}
```suggestion
                 * Verhalten siehe {@link StateMachineInterceptor#preTransition(StateContext)}.
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +                 * Die Rückgabe des Wertes null führt in der StateMachine zum Ergebnis {@link StateMachineEventResult.ResultType#DENIED}
```suggestion
                 * Die Rückgabe des Wertes null führt in der StateMachine zum Ergebnis {@link StateMachineEventResult.ResultType#DENIED}.
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * Leitet eine Statusänderung ein mit dem übergebenem Event
```suggestion
     * Leitet mit dem übergebenem Event eine Statusänderung ein.
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param id           vom Typ {@link UUID} um die Abfrage aus der DB zu holen.
```suggestion
     * @param id vom Typ {@link UUID} um die Abfrage aus der DB zu holen
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param event        vom Typ {@link StatusAbfrageEvents} um eine Statusänderung durchzuführen
```suggestion
     * @param event vom Typ {@link StatusAbfrageEvents} um eine Statusänderung durchzuführen
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/configuration/StateMachineConfiguration.java
> +     * @param states konfiguriert alle Statis der State Machine
```suggestion
     * @param states konfiguriert alle Status der State Machine
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @param stateMachine vom Typ {@link StateMachine} welches den aktuellen Status plus alle Statis enthält
Plural von Status ist Status. Stati oder Statusse existiert nicht siehe Duden
```suggestion
     * @param stateMachine vom Typ {@link StateMachine} welche den aktuellen Status plus alle Status enthält
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * @throws EntityNotFoundException falls kein AbfrageId Header gefunden wurde
```suggestion
     * @throws EntityNotFoundException falls kein AbfrageId Header gefunden wird
```

2023-02-01 14:34 UTC, DomixD commented on src/main/java/de/muenchen/isi/infrastructure/entity/enums/lookup/StatusAbfrage.java
>      ABBRUCH("Abbruch");
Laut Datenmodell
```suggestion
    ABBRUCH("abbruch");
```

2023-02-01 14:47 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @PutMapping("infrastruktur-abfrage/{id}/abbrechen")
Ja, das stimmt.

2023-02-02 13:40 UTC, boal requested changes

2023-02-02 13:40 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +import static de.muenchen.isi.api.controller.AbfrageStatusController.CONTROLLER_PATH;
Die Konstante CONTROLLER_PATH wird nur im Controller verwendet und der String kann direkt in die Annotation geschrieben werden.

2023-02-02 13:54 UTC, boal requested changes

2023-02-02 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
>      @PutMapping("infrastruktur-abfrage/{id}/freigabe")
Der Endpoint passt nicht. Bitte alle Endpunkte prüfen.

2023-02-02 14:08 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
>      @PutMapping("infrastruktur-abfrage/{id}/freigabe")
Alle endpunkte funktionieren noch genauso wie davor

2023-02-02 14:31 UTC, boal approved these changes

2023-02-02 14:42 UTC, boal submitted a review, later dismissed

2023-02-13 13:17 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT ->  Die Abfrage konnte aufgrund des aktuellen Status oder des bereits existierenden Abfragenamen nicht zur Bearbeitung zurückgeg
Hier hat sich ein Leerzeichen zu viel vor dem `Die Abfrage...` eingeschlichen :DD

2023-02-13 13:19 UTC, DomixD approved these changes, later dismissed

2023-02-17 07:09 UTC, boal approved these changes

2023-03-08 09:26 UTC, TiagoKocevar commented
Diese Pull Request wird geschlossen da der Branch von ISI-474 denn Zustandsautomaten schon gemerged hat

2023-03-08 09:26 UTC, closed without merging