ISI-837 Auslösen von Sobon Berechnung und Auswahl des Sobon wichtigem Fördermix
it-at-m/isi-backend pull request #149
Opened 2024-03-06 12:21 UTC by TiagoKocevar

**Description**

Neue Attribute isASobonBerechnung (boolean) und sobonFoerdermix (Foerdermix).

Wenn isASobonBerechnung wahr ist soll eine SobonBerechnung ausgeführt werden. Aber nur wenn auch der sobonFoerdermix gesetzt wurde. 

Dann wird der sobonFoerdermix als Basis hergenommen für die Berechnung. 

Validation hinzugefügt das sobonFoerdermix einen Wert haben muss wenn isASobonBerechnung wahr ist. 

Außerdem Validation abgeändert bei der Fördermixklasse da bei der Abfragevariante die Felder sobonFoerdermix und isASobonBerechnung null sein dürfen. 

**Reference**

Issues #837

2024-03-12 11:22 UTC, boal requested changes

2024-03-12 11:22 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/SobonFoerdermixBauleitplanverfahrenAVValid.java
> +@Constraint(validatedBy = SobonFoerdermixBauleitplanverfahrenAVValidator.class)
Typo on `SobonFoerdermixBauleitplanverfahrenAVValidator` -> `AVValidator`?

2024-03-12 11:22 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/BaurateDto.java
> +    @FoerdermixNotEmptyValid
Bei der Validierungsannotation kann der Postfix `Valid` entfernt werden.

2024-03-12 11:22 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/abfrageInBearbeitungSachbearbeitung/AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDto.java
> +
Evtl die beiden Variablen in einer Klasse auslagern welche dann bei den Entitäöten als Embedabble definiert sind. Diese Klasse dann anstelle der beiden Attribute in die Dto/Models/Entitäten einfügen.

Somit braucht nur eine Validierungslogik für die neue Klasse geschrieben werden und die einzelnen Validatoren und Validieirungsannotationen je Abfragetyp können entfallen.

2024-03-12 11:22 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/calculation/CalculationService.java
> +    public boolean hasRightCoonditionsForLangfristigeSobonBerechnung(
Der Methodenname sagt nichts über die fachliche Logik aus.

Der Methodenname sollte dem entsprechen was in der Methode geprüft wird.

evtl `doSobonberechung`?

2024-03-12 11:22 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/calculation/CalculationService.java
> +            ObjectUtils.isNotEmpty(abfragevarianteBauleitplanverfahren.getIsASobonBerechnung()) &&
Die boolsche Ausdruck welcher `getIsASobonBerechnung()` prüft kann mit den Apache-Commons `BooleanUtils` auf eine Zeile reduziert werden.

2024-03-12 11:22 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/AbfragevarianteWeiteresVerfahren.java
> +    private Boolean isASobonBerechnung;
Wie oben beschrieben die beiden Attribute auf eine Embeddable zusammenfassen.

2024-03-12 13:54 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/validation/SobonFoerdermixBauleitplanverfahrenAVValid.java
> +@Constraint(validatedBy = SobonFoerdermixBauleitplanverfahrenAVValidator.class)
Ich habe AVVValidatior weil AV für Abfragevariante (AV) steht. 

Anders wäre der name viel zu lange geworden deswegen habe ich ihn so genannt

2024-03-13 10:58 UTC, boal requested changes

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/FoerdermixNotEmptyValidator.java
> +public class FoerdermixNotEmptyValidator implements ConstraintValidator<FoerdermixNotEmptyValid, FoerdermixDto> {
Die Klasse Unit-Testen.

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/calculation/CalculationService.java
> +    public boolean doSobonberechung(
Der Name `doSobonBerechnung` deutet darauf hin, dass hier eine Berechnung durchgeführt wird. Tatsächliche wird geprüft ob Berechnet werden soll.

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/calculation/CalculationService.java
> +    public boolean doSobonberechung(
Der Name `doSobonBerechnung` deutet darauf hin, dass hier eine Berechnung durchgeführt wird. Tatsächliche wird geprüft ob Berechnet werden soll.

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/calculation/CalculationService.java
> +    public boolean doSobonberechung(
Evtl `shouldSobonBerechnungPerformed` oder `shouldSobonBerechnugCarriedOut`, ...

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/calculation/CalculationService.java
> +    public boolean doSobonberechung(
Evtl `shouldSobonBerechnungPerformed` oder `shouldSobonBerechnugCarriedOut`, ...

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/AbfragevarianteWeiteresVerfahren.java
> +    @Embedded
Das Attribute override hierher verlagern.

```java
@AttributeOverrides(
        {
            @AttributeOverride(
                name = "sobonBerechnung.isASobonBerechnung",
                column = @Column(name = "is_a_sobon_berechnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonBerechnung.bezeichnung",
                column = @Column(name = "sobon_foerdermix_bezeichnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonBerechnung.bezeichnungJahr",
                column = @Column(name = "sobon_foerdermix_bezeichnung_jahr", nullable = true)
            ),
        }
    )
```

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/common/SobonBerechnung.java
> +    @AttributeOverrides(
Attribute override verlagern.

2024-03-13 10:58 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/AbfragevarianteBauleitplanverfahren.java
> +    @Embedded
Das Attribute override hierher verlagern.

```java
@AttributeOverrides(
        {
            @AttributeOverride(
                name = "sobonBerechnung.isASobonBerechnung",
                column = @Column(name = "is_a_sobon_berechnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonBerechnung.bezeichnung",
                column = @Column(name = "sobon_foerdermix_bezeichnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonBerechnung.bezeichnungJahr",
                column = @Column(name = "sobon_foerdermix_bezeichnung_jahr", nullable = true)
            ),
        }
    )
```

2024-03-13 11:51 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/validation/FoerdermixNotEmptyValidator.java
> +public class FoerdermixNotEmptyValidator implements ConstraintValidator<FoerdermixNotEmptyValid, FoerdermixDto> {
Wurde erledigt in SobonBerechnungValidatorTest.java

2024-03-13 12:14 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/infrastructure/entity/AbfragevarianteBauleitplanverfahren.java
> +    @Embedded
```
    @AttributeOverrides(
        {
            @AttributeOverride(
                name = "sobonBerechnung.isASobonBerechnung",
                column = @Column(name = "is_a_sobon_berechnung", nullable = true)
            ),
        }
    )
    private SobonBerechnung sobonBerechnung;
```
    
    Ich kann denn Boolean Wert istASobonberechnung in der Abfragevariante überschreiben aber die Attribute:
    sobonBerechnung.bezeichnungJahr
    sobonBerechnung.bezeichnung
    
```
     @AttributeOverride(
                name = "sobonBerechnung.bezeichnung",
                column = @Column(name = "sobon_foerdermix_bezeichnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonBerechnung.bezeichnungJahr",
                column = @Column(name = "sobon_foerdermix_bezeichnung_jahr", nullable = true)
            ),
```
         Die Attribute wurden dann durch JPA nicht erstellt und auch wenn ich "sobonBerechnung.sobonFoerdermix.bezeichnungJahr" &   "sobonBerechnung.sobonFoerdermix.bezeichnung" geschrieben habe konnte er es nicht erstellen. 
         
         Deswegen habe ich diese beiden @AttriubteOverrides in der SobonBerechnung Klasse gelassen

2024-03-13 12:26 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/AbfragevarianteBauleitplanverfahren.java
> +    @Embedded
Es muss dann heißen:

```java

@AttributeOverrides(
        {
            @AttributeOverride(
                name = "isASobonBerechnung",
                column = @Column(name = "is_a_sobon_berechnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonFoerdermix.bezeichnung",
                column = @Column(name = "sobon_foerdermix_bezeichnung", nullable = true)
            ),
            @AttributeOverride(
                name = "sobonFoerdermix.bezeichnungJahr",
                column = @Column(name = "sobon_foerdermix_bezeichnung_jahr", nullable = true)
            ),
        }
    )

```

2024-03-13 13:30 UTC, boal approved these changes, later dismissed

2024-03-14 06:55 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/FoerdermixNotEmptyValidator.java
> +public class FoerdermixNotEmptyValidator implements ConstraintValidator<FoerdermixNotEmptyValid, FoerdermixDto> {
Jede Klasse soll in ihrem eigenen Unit-Test getestet werden. Somit ist sofort ersichtlich, welcher Klasse fehlerhaft ist.

Es sind auch die Grenzfälle abzutesten.

2024-03-14 08:45 UTC, boal approved these changes

2024-03-18 08:12 UTC, merged