ISI-1305-Metabase-und-das-zugehörige-Reporting-EAI-in-Prod-Dev-TA-und-Demoumgebung-ausrollen
it-at-m/isi-backend pull request #156
Opened 2024-04-03 08:51 UTC by lhmAschaenz

**Description**

Um Endpoint _stammdaten/metabase-reporting_ erweitert. Hier werden die _metabase/reporting_ Angaben in den `application-<Umgebung>.yml` ausgelesen und dem Frontend zur Verfügung gestellt. Diese Angaben werden für den Einsprung aus ISI in die Metabase Dashboard Links benötigt. Entsprechende Unit-Tests sind implementiert.

**Reference**

Issues #1305

2024-04-03 12:01 UTC, TiagoKocevar requested changes

2024-04-03 12:01 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/MetabaseReportingService.java
> +    public MetabaseReportingModel getMetabaseReporting() {
Das wäre dann die abgeänderte Methode. 

Dann könnte man auch die Klassenvariablen von dieser Service Klasse löschen

```
 public MetabaseReportingModel getMetabaseReporting( @Value("${metabase.reporting.url}") final String url,
        @Value("${metabase.reporting.reports.report.bedarfe}") final String reportBedarfe,
        @Value(
            "${metabase.reporting.reports.report.spitzenbedarfe.planungsursaechlich}"
        ) final String reportSpitzenbedarfePlanungsursaechlich,
        @Value(
            "${metabase.reporting.reports.report.spitzenbedarfe.sobon.ursaechlich}"
        ) final String reportSpitzenbedarfeSobonUrsaechlich,
        @Value("${metabase.reporting.reports.report.wohneinheiten}") final String reportWohneinheiten) {
        final var metabaseReportingModel = new MetabaseReportingModel();
        metabaseReportingModel.setUrl(urll);
        metabaseReportingModel.setReportBedarfe(reportBedarfe);
        metabaseReportingModel.setReportSpitzenbedarfePlanungsursaechlich(reportSpitzenbedarfePlanungsursaechlich);
        metabaseReportingModel.setReportSpitzenbedarfeSobonUrsaechlich(reportSpitzenbedarfeSobonUrsaechlich);
        metabaseReportingModel.setReportWohneinheiten(reportWohneinheiten);
        return metabaseReportingModel;
    }
```

2024-04-03 12:58 UTC, lhmAschaenz commented on src/main/java/de/muenchen/isi/domain/service/stammdaten/MetabaseReportingService.java
> +    public MetabaseReportingModel getMetabaseReporting() {
wie besprochen belassen wir die Implementierung, da der Aufruf des Service im Controller nicht mehr geht.

2024-04-05 08:20 UTC, TiagoKocevar approved these changes
👍🏽

2024-04-08 13:53 UTC, merged