ISI-1724
it-at-m/isi-backend pull request #187
Opened 2024-08-01 13:38 UTC by boal

**Description**

Findet der Zustandsübergang "SPEICHERN_VON_SOZIALINFRASTRUKTUR_VERSORGUNG" statt, dann wird eine Mail an die Personen im Verteiler Sachbearbeitung und Bedarfsmeldung verschickt, dass die Abfrage erledigt ist.

**Reference**

ISI-1724

2024-08-01 14:19 UTC, TiagoKocevar requested changes

2024-08-01 14:19 UTC, TiagoKocevar commented on src/main/resources/application.yml
> +      test: "Die Abfrage ist abgeschlossen.\n\nAbfrage: "
Anstatt `test` sollte es `text` heißen

2024-08-02 06:13 UTC, boal commented on src/main/resources/application.yml
> +      test: "Die Abfrage ist abgeschlossen.\n\nAbfrage: "
Oh ja! Der Klassiker! Ich habe es angepasst.

2024-08-02 06:51 UTC, TiagoKocevar approved these changes
👍🏽

2024-08-06 12:09 UTC, merged