ISI-474-Auto-Statusübergänge
it-at-m/isi-backend pull request #28
Opened 2023-02-23 09:36 UTC by TiagoKocevar

**Description**

Damit der Status nur noch über den Zustandsautomaten abgeändert werden soll müssen die Create und Update Methoden noch abgeändert werden. 

Bei der Create Methode wird nun im Backend automatisch der Status ANGELEGT gesetzt. 

Die Update Methoden habe ich aufgeteilt in einmal "Update With Status" und "Update Without Status". 

"Update With Status": Methode Updated die Abfrage mit dem Status dazu
"Update Without Status": Methode Updated alle Werte außer den Status.

**Reference**

Issues #474

2023-02-24 07:21 UTC, boal requested changes

2023-02-24 07:21 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        InfrastrukturabfrageModel abfragedb = this.getInfrastrukturabfrageById(abfrage.getId());
Die Lösung ist richtig gut. Einfach und sehr effektiv! :-)

Attribut "abfragedb" final und in Camelcase. -> abfrageDb

2023-02-24 08:23 UTC, boal requested changes

2023-02-24 08:23 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
>      }
Evtl. macht es bei `saveInfrastrukturabfrage` bei einer ID mit Wert `null` Sinn den Status dann auf den initialen Wert zu setzen. Somit wird sichergestellt, dass eine neue Abfrage immer mit dem initialen Status gespeichert wird.

2023-02-24 09:38 UTC, boal approved these changes, later dismissed

2023-03-08 09:16 UTC, banzuu approved these changes

2023-03-08 09:25 UTC, merged