ISI-480 Statuswechsel in einer Infrastrukturabfrage
it-at-m/isi-backend pull request #33
Opened 2023-04-03 07:46 UTC by TiagoKocevar

**Description**

Erweiterung der `AbfrageStatusService.java` Klasse um die Methode `getStatusAbfrageEventsBasedOnStateAndRole` die Anhand des aktuellen Status der Abfrage und der Authorities des Nutzers die möglichen Transitions (`StatusabfrageEvents.java`) anzeigen.

Die `TransitionModel` Klasse die zurückgegeben wird (von der Methode) hat drei Atrribute:

1.  url -> Ist der URL Pfad für den dazugehörigen Pfad (im Frontend wird dieser URL Pfad angehängt)
2. buttonName -> Wie der Button im Frontend heißen soll
3. index -> Gibt an an welcher Position der Button hat im Frontend

Außerdem gibt es noch eine `AuthenticationUtils` Klasse welche aus dem aktuellen Security Context die Authorities des Nutzers holt und in eine ArrayList schreibt.

Anhand der Authorities wird zu StatusabfrageEvents gemappt in der Methode `getRolesAndEventsMap`

**Reference**

Issues #480

2023-04-03 13:54 UTC, boal requested changes

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        throws EntityNotFoundException {
Zeilenumbruch entfernen. Throws hinter der schließenden Klammer des Parameters.

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * Entnimmt alle möglichen Statusänderungen aus dem aktuellen Status und den Authorities des Nutzers.
Was bedeutet "Entnimmt alle möglichen Statusänderunge"?
Hier ist nicht klar was die Methode macht.

Beschreiben, dass auf Basis der möglichen Statusübergeänge des aktullen Status der Abfrage und der für den Nutzer erluabten Statusübergänge die möglichen Statusübergänge ermittelt werden.

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        List<AuthoritiesEnum> userRolesAuthorities = AuthenticationUtils.getUserAuthorities();
Das Attribut `userRolesAuthorities `  schreibt, dass es sich hier um ROllen handelt. Es werden jedoch die Rechte (Authorithies) hier gesammelt.

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        Map<AuthoritiesEnum, StatusAbfrageEvents> rolesAndMatchingEvent = getRolesAndEventsMap();
Der Benennungsbestandteil `Role` in den Variablen und Methoden auf Authorities ändern.

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        List<TransitionModel> possibleTransitionsModel = new ArrayList<>();
Typo in Variable `possibleTransitionsModel` -> `possibleTransitionModels `

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        for (AuthoritiesEnum userRole : userRolesAuthorities) {
Evtl die For-Schleife in eine eigene Methode auslagern welche die möglichen AbfrageEvents basierend auf den Athorities extrahiert und dann die neue Methode hier aufrufen.

z.B. `getStatusAbfrageEventsForAuthorities(final List<AuthoritiesEnum> authorties)`

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        for (StatusAbfrageEvents event : matchingAbfrageEvents) {
Die For-SChleife und das anschließende sortieren besser mit einem Stream machen. Wo immer möglich Streams statt schleifen verwenden.

```java
return matchingAbfrageEvents.stream()
   .map(event -> {
            TransitionModel transitionModel = new TransitionModel();
            transitionModel.setUrl(event.getUrl());
            transitionModel.setButtonName(event.getButtonName());
            transitionModel.setIndex(event.getIndex());
})
.sort(Comparator.comparingInt(TransitionModel::getIndex))

```

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * Entnimmt alle möglichen Statusänderungen aus dem aktuellen Status.
Anstelle `Entnimmt` besser `Ermittelt`.

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        final Map<AuthoritiesEnum, StatusAbfrageEvents> rolesAndEvents = new HashMap<>();
Hat es einen Grund weshalb nicht alle Events mit den Authorizies gemappt sind?

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +    public List<StatusAbfrageEvents> getStatusAbfrageEventsBasedOnState(final UUID id) throws EntityNotFoundException {
Falls diese Methode nicht in andernen Klassen verwendet wird, besser als `protected` definieren.

2023-04-03 13:54 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/util/AuthenticationUtils.java
> +     * Die Methode extrahiert die Nutzer Rollen aus dem {@link DefaultOAuth2AuthenticatedPrincipal}
Werden hier nur Rollen extrahiert?

2023-04-03 14:12 UTC, boal requested changes

2023-04-03 14:12 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageStatusController.java
> +    @Operation(summary = "Hollt alle möglichen StatusAbfrage Transitions auf Basis der Rolle und des akutellen Status")
Typos und Rolle anstelle Authorities.

2023-04-03 14:15 UTC, boal requested changes

2023-04-03 14:15 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * Definiert eine {@link Map} welche die {@link AuthoritiesEnum} mit den dazugehörigten {@link StatusAbfrageEvents} verknüpft.
Beschreiben, dass hier die zentrale Stelle zum Mapping der Authorities und Transitions liegt.

Alternativ die Transiation zum Authority-Enum als Variable zuordnen.

2023-04-04 11:56 UTC, banzuu approved these changes, later dismissed

2023-04-04 14:27 UTC, banzuu submitted a review, later dismissed

2023-04-21 11:24 UTC, banzuu submitted a review, later dismissed

2023-04-27 08:18 UTC, boal requested changes

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/api/mapper/TransitionApiMapper.java
> +    TransitionModel dto2Model(TransitionDto dto);
Wird die Mappingmethode vom Dto zum Model benötigt? Falls nicht entfernen.

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        List<StatusAbfrageEvents> possibleAbfrageEventsBasedOnAuthorities;
Die Variable wird hier definiert und erst zwei Zeilen darunter mit einer Instanz versehen. Die Variable dort definierren wo diese zum ersten mal benötigt wird.

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        Map<AuthoritiesEnum, StatusAbfrageEvents> authoritiesAndMatchingEvent = getAuthoritiesAndEventsMap();
Da die Variable `authoritiesAndMatchingEvent ` in dieser Methode nur einmal bei Methode `getStatusAbfrageEventsForAuthorities` verwendet wird, kann der Methodenaufruf `getAuthoritiesAndEventsMap` zum instantiieren der Variable in der Methode`getStatusAbfrageEventsForAuthorities` werden.

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        List<StatusAbfrageEvents> matchingAbfrageEvents = new ArrayList<>(getStatusAbfrageEventsBasedOnState(id));
Die Methode  `getStatusAbfrageEventsBasedOnState` gibt bereits eine Liste zurück. Somit muss diese nicht mehr als ArrayList instantiiert werden.

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        matchingAbfrageEvents.retainAll(possibleAbfrageEventsBasedOnAuthorities);
Das ist echt gut gemacht! :-)

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +     * Ermittelt anhand der vom Benutzer besessenen Authorities, welche {@link StatusAbfrageEvents} für den Benutzer erlaubt sind.
Besser Nutzerneutral schreiben:

`Ermittelt anhand der im SecurityContext` vorhandenen Authorities, welche StatusabfrageEvents erlaubt sind.

2023-04-27 08:18 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageStatusService.java
> +        for (AuthoritiesEnum authority : authorities) {
Evtl in einem Stream abbilden. Streams lesen sich meistens leichter als for oder while-Loops.
Evtl.:
```java
        return authorities.stream()
                .map(authoritiesAndMatchingEvent::get)
                .filter(Objects::nonNull)
                .collect(Collectors.toList());

```

2023-04-27 12:33 UTC, boal approved these changes

2023-04-27 12:33 UTC, boal submitted a review, later dismissed

2023-04-27 14:48 UTC, boal approved these changes

2023-04-28 07:22 UTC, merged