Isi 492 generische implementierung foerdermix
it-at-m/isi-backend pull request #34
Opened 2023-04-03 12:55 UTC by DomixD

**Description**

Der Fördermix wurde generisch implementiert. Das heißt Jeder Fördermix kann eine beliebige Anzahl an Förderarten besitzen.

**Reference**

Issues ISI-492

2023-04-04 07:26 UTC, boal requested changes

2023-04-04 07:26 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/BaurateController.java
> +    @Transactional
Hier besser `@Transactional(readOnly = true)``verwenden. Da hier wie bei getBaurateByID ebenfalls nur Lesezugriffe auf die DB getätigt werden.

2023-04-04 07:26 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/stammdaten/FoerdermixStammController.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT -> Fördermix konnte nicht erstellt werden, da für die Bezeichnung im angegebenen Jahr bereits ein anderer Fördermix existiert.",
Über das Backend nochaml den Linter drüberlaufen lassen. -> npm run lint

2023-04-04 07:26 UTC, boal commented on src/main/java/de/muenchen/isi/api/validation/HasFoerdermixRequiredSumValidator.java
> +            var tmp = ObjectUtils.defaultIfNull(foederart.getAnteilProzent(), BigDecimal.ZERO);
Die Variable `tmp` besser in `summand` umbenennen und final setzen. Da diese zur `sumFoerdermix` addiert wird.

Alternativ kann auch ein Stream verwendet werden.

```java
        final BigDecimal sumFoerdermix = foerderarten.stream()
                .map(foerderart -> ObjectUtils.defaultIfNull(foerderart.getAnteilProzent(), BigDecimal.ZERO))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

```

2023-04-04 07:26 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Baurate.java
> +    @OneToOne(cascade = CascadeType.ALL)
`CascadeType.ALL`:

Wird die Baurate gelöscht wird somit auch der Fördermix in der Fördermixtabelle gelöscht. Der Fördermixstamm verliert somit seine referenzierte Entität.

Im umgekehrten Fall beim Löschen eines Fördermixstamms verliert die Baurate ebenso seine referenzierte Entität.

2023-04-04 07:26 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/stammdaten/FoerdermixStamm.java
> +    @OneToOne(cascade = CascadeType.ALL)
CascadeType.ALL:

Wird der Fördermixstamm gelöscht wird somit auch der Fördermix in der Fördermixtabelle gelöscht. Die Baurate verliert somit seine referenzierte Entität.

Im umgekehrten Fall beim Löschen einer Baurate verliert der Fördermixstamm  ebenso seine referenzierte Entität.

2023-04-04 07:26 UTC, boal commented on src/test/java/de/muenchen/isi/api/validation/HasFoerdermixRequiredSumValidatorTest.java
> +>>>>>>> dev
Hier sind noch überbleibsel eines Merge-Conflicts vorhanden.

2023-04-04 07:26 UTC, boal commented on src/test/java/de/muenchen/isi/api/validation/HasFoerdermixRequiredSumValidatorTest.java
> +=======
Hier sind noch überbleibsel eines Merge-Conflicts vorhanden.

2023-04-04 07:26 UTC, boal commented on src/main/java/de/muenchen/isi/infrastructure/entity/Baurate.java
> +    @OneToOne(cascade = CascadeType.ALL)
Vermutlich ist es besser wenn der Fördermix mit den darin enthaltenen Förderarten als @Embedabble behandelt wird.

In der GUI für den User (nicht Admin) wird dann der gewünschte FördermixStamm ausgewählt. Bei der Auswahl wird das Attribut Fördermix einfach kopiert und der Baurate zugewiesen. Somit existiert die Baurate mit einer Kopie eines Fördermixes (ausgewählt aus einem Fördermixstamm). Folglich besteht nicht mehr die Gefahr, eines CascadeDelete und somit eines Verlusts einer Referenz.

2023-04-05 09:06 UTC, DomixD commented on src/main/java/de/muenchen/isi/api/controller/stammdaten/FoerdermixStammController.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT -> Fördermix konnte nicht erstellt werden, da für die Bezeichnung im angegebenen Jahr bereits ein anderer Fördermix existiert.",
Da hat er bei mir nichts angepasst oder musste man da noch etwas einstellen?

2023-04-05 09:20 UTC, DomixD commented on src/main/java/de/muenchen/isi/infrastructure/entity/Baurate.java
> +    @OneToOne(cascade = CascadeType.ALL)
Aber hatten wir dann nicht das Problem mit dem detached? Weshalb ich das ja zu einer OneToOne Beziehung umgebaut hatte🤔

2023-04-05 10:19 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/stammdaten/FoerdermixStammController.java
> +            @ApiResponse(responseCode = "409", description = "CONFLICT -> Fördermix konnte nicht erstellt werden, da für die Bezeichnung im angegebenen Jahr bereits ein anderer Fördermix existiert.",
Du musst erst einen npm install machen.

2023-04-12 11:17 UTC, boal approved these changes

2023-04-24 05:55 UTC, merged