Name Abfragevariante hinzugefügt🎉
it-at-m/isi-backend pull request #35
Opened 2023-04-03 13:34 UTC by TiagoKocevar

**Description**

Attribut Abfragevariante Name hinzugefügt. Auch die Überprüfung das in einer Abfrage jede Abfragevariante einen Uniquen Namen haben muss. 

**Reference**

Issues #510

2023-04-04 07:43 UTC, boal requested changes

2023-04-04 07:43 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
>       * @throws OptimisticLockingException falls in der Anwendung bereits eine neuere Version der Entität gespeichert ist
DataIntegrityViolationException ist nicht in den Javadoc der Methoden beschrieben.

2023-04-04 07:43 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +                throw new DataIntegrityViolationException(message);
Keine Framework-Exceptions werfen. Hier die UniqueViolationException analog zum Fördermixstamm verwenden.

2023-04-04 07:43 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +     * @throws EntityNotFoundException    falls die Abfrage identifiziert durch die {@link InfrastrukturabfrageModel#getId()} nicht gefunden wird
DataIntegrityViolationException ist nicht in den Javadoc der Methoden beschrieben.

2023-04-04 07:43 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +     * @throws EntityNotFoundException    falls die Abfrage identifiziert durch die {@link InfrastrukturabfrageModel#getId()} nicht gefunden wird
DataIntegrityViolationException ist nicht in den Javadoc der Methoden beschrieben.

2023-04-04 12:05 UTC, banzuu commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +     * @throws UniqueViolationException   falls der Name der Abfrage {@link InfrastrukturabfrageModel#getAbfrage().getNameAbfrage} ()} bereits vorhanden ist
Müsste die Beschreibung hier nicht die Gleiche wie bei `updateInfrastrukturabfrageWithoutStatus` sein?

2023-04-04 12:06 UTC, banzuu commented
Muss nicht auch der DatabaseFiller angepasst werden?

2023-04-04 14:19 UTC, banzuu approved these changes

2023-04-11 13:45 UTC, boal approved these changes

2023-04-12 05:57 UTC, merged