ISI-45/ISI-555 Abfragevariante Relevant markieren und Bug Fix
it-at-m/isi-backend pull request #52
Opened 2023-05-31 11:07 UTC by TiagoKocevar

In dieser Story habe ich das Feature implementiert Abfragevarianten als Relevant zu markieren. Dies geschieht über die Abfrageservice Klasse.

Ich habe auch noch 3 neue Klassen hinzugefügt die wir in Zukunft noch gebrauchen werden aber mit der Story nicht viel zu tun haben. Es geht um die Klassen AbfrageerstellungInfrastrukturabfrageAngelegt, AbfrageerstellungAbfragevarainteAngelegt, AbfrageerstellungAbfrageAngelegt. Diese haben alle Attribute die der Abfrageersteller editieren darf im Status ANGELEGT.

In Zukunft wird es abhängig von der Rolle und dem Status noch weitere Klassen dieser Art geben. Dies habe ich abgesprochen mit Albrecht und Boxi.

Außerdem habe ich den Bug gefixt mit den nicht funktionierenden Statusänderungen dies geschieht dadurch das ich das Speichern bevor ein Statusübergang passiert entfernt habe da der aktuelle PATCH nur im Status ANGELEGT und mit der Rolle Abfrageersteller funktioniert.

2023-06-01 12:01 UTC, boal requested changes

2023-06-01 12:01 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +    @Operation(summary = "Aktualisierung einer Infrastrukturabfrage im Status IN_BEARBEITUNG_SACHBEARBEITUNG.")
Die Beschreibung ist nicht kiorrekt.

Hier wird die Abfragevariante gegeben in der als Relevant markiert.

2023-06-01 12:01 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +                description = "CONFLICT -> Abfrage konnte nicht erstellt werden, da der Name der Abfrage oder Abfragevariante bereits existiert.",
Kann dieser Fehler hier auftreten?

2023-06-01 12:01 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +                description = "CUSTOM INTERNAL SERVER ERROR -> Die Dateien konnten nicht gelöscht werden.",
Kann dieser Fehler hier auftreten?

2023-06-01 12:01 UTC, boal commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +                description = "NOT_FOUND -> Es gibt keine Abfrage mit der ID.",
Kann dies auch bei der Abfragevariante passiere?

2023-06-01 12:02 UTC, boal commented
Hab bis jetzt nur eine kleinen Teil ein Review unterzogen und die vier obigen Sachen gefunden.

2023-06-02 10:27 UTC, boal requested changes

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/mapper/AbfrageDomainMapper.java
> +    @AfterMapping
Javadoc welche beschriebt, dass hier das manuelle Mapping der Abfragevarianten stattfindet welches im Mapper durch `@Mapping(target = "abfragevarianten", ignore = true)` unterdrückt wird.

Des Weiteren kurz beschreiben, was der Grund für das manuelle Mapping ist.

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +     * @throws FileHandlingWithS3FailedException
Werden die beiden Exception `FileHandlingFailedException` und `FileHandlingWithS3FailedException` hier geworfen geworfen bzw. sind die hier relevant? Falls nicht entfernen.

Gilt auch für `throws`-Statement der Methode.

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        dokumentService.deleteDokumenteFromOriginalDokumentenListWhichAreMissingInParameterAdaptedDokumentenListe(
Hier findet keine Änderung bei den Dokumenten statt. Der Code wird somit nicht benötigt.

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        abfragevariante.setRelevant(!abfragevariante.isRelevant());
Sollte das Relevantsetzen der Abfragevariante nicht erst nach dem Check `checkForUniqueRelevantAbfragevariante` geschehen?

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        abfrage.getAbfrage().setStatusAbfrage(abfrage.getAbfrage().getStatusAbfrage());
Ist das setzen des Status hier nötigt?

Der Status der in der `abfrage` vorhanden ist wird wieder in der selben `abfrage` gesetzt.

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +                "Die Abfrage ist keinem Bauvorhaben zugeordnet deswegen können Sie keine Abfragevariante als Relevant markieren."
Text ohne direkte Ansprache (Sie) schreiben.

`"Die Abfrage ist keinem Bauvorhaben zugeordnet. Somit kann keine Abfragevariante als Relevant markiert werden."`

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        relevanteAbfrage[0] = "false";
Keinen Boolean in String-Array setzen!

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +        String[] relevanteAbfrage = new String[3];
Keinen dreidimensionalen Array für unterschiedliche Attribute verwenden!

Besser drei Attribute.

```java
final boolean foundRelevantAbfragevariante;
final String nameRelevantAbfrage;
final String nameRelevantAbfragevariante;

```

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +    private void checkForUniqueRelevantAbfragevariante(final InfrastrukturabfrageModel abfrage)
In Methodenname beschreiben was diese macht.

Bei einem Check würde ich ein boolean als Rückgabewert erwarten.

Eher `throwExceptionIfNoBauvorhabenIsReferencedOrAnAbfragevarianteIsRelevant` oder ähnlich.

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/domain/service/AbfrageService.java
> +            throw new UniqueViolationException(errorMessage);
Fehler in den Logs ausgegeben.

```java
log.error(errorMessage, exception)

```

2023-06-02 10:27 UTC, boal commented on src/main/java/de/muenchen/isi/security/AuthenticationUtils.java
> +                            log.error("Authority {} nicht in AuthoritiesEnum gefunden", authority.getAuthority());
`Authority {} nicht in AuthoritiesEnum vorhanden.`

2023-06-02 10:39 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +                description = "CONFLICT -> Abfrage konnte nicht erstellt werden, da der Name der Abfrage oder Abfragevariante bereits existiert.",
Nein werde ich verbessern

2023-06-02 10:39 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +                description = "CUSTOM INTERNAL SERVER ERROR -> Die Dateien konnten nicht gelöscht werden.",
Nein werde ich verbessern

2023-06-02 10:39 UTC, TiagoKocevar commented on src/main/java/de/muenchen/isi/api/controller/AbfrageController.java
> +                description = "NOT_FOUND -> Es gibt keine Abfrage mit der ID.",
Ja das kann auch in der Abfragevariante passieren werde die beschreibung anpassen

2023-06-05 05:46 UTC, boal commented
Unit test schlagen fehl

2023-06-05 11:14 UTC, banzuu approved these changes

2023-06-05 11:26 UTC, boal approved these changes

2023-06-07 07:59 UTC, merged