ISI-619 Validierung bezüglich technischer und nichttechnischer Baugebiete sowie Bauabschnitte
it-at-m/isi-backend pull request #89
Opened 2023-09-05 17:29 UTC by TiagoKocevar

Description

Hinzufügen einer Annotation welche die in der ISI-619 beschriebenen Anforderungen überprüft.

Reference

Issues #619

2023-09-11 11:47 UTC, banzuu submitted a review, later dismissed

2023-09-13 09:03 UTC, boal requested changes

2023-09-13 09:03 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfragevarianteDto.java
>  public class AbfragevarianteDto extends BaseEntityDto {
Ist die Validierung mit `@TechnicalAttributesValid` bei der AbfragevarianteDTO korrekt?

Richtig wäre doch die `AbfragevarianteAngelegtDto`, da dieses DTO zum persistieren verwendet wird und auch die Basisklasse für die zu persistierende  `AbfragevarianteInBearbeitungSachbearbeitungDto` ist.

2023-09-18 14:19 UTC, boal approved these changes

2023-09-18 14:19 UTC, boal commented on src/main/java/de/muenchen/isi/api/dto/AbfragevarianteDto.java
>  public class AbfragevarianteDto extends BaseEntityDto {
Angepasst.

Die korrekte Funktionalität bei der `AbfragevarianteAngelegtDto` und `AbfragevarianteInBearbeitungSachbearbeitungDto ` ist durch Erstellung eines entsprechenden AbfrageDtos zu Triggern. Dieses DTO ist mit dem Validator zu validieren.

```java
Validation.buildDefaultValidatorFactory().getValidator();
```

2023-09-19 11:26 UTC, merged